apiVersion: v1
kind: Service
metadata:
  name: User Experience Service
  labels:
    app: User Experience Service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: User Experience Service