---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Transportation Service
  labels:
    app: Transportation Service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Transportation Service
  template:
    metadata:
      labels:
        app: Transportation Service
    spec:
      containers:
        - name: Transportation Service
          image: username/Transportation Service:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Payment Service
  labels:
    app: Payment Service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Payment Service
  template:
    metadata:
      labels:
        app: Payment Service
    spec:
      containers:
        - name: Payment Service
          image: username/Payment Service:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Vehicle Service
  labels:
    app: Vehicle Service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Vehicle Service
  template:
    metadata:
      labels:
        app: Vehicle Service
    spec:
      containers:
        - name: Vehicle Service
          image: username/Vehicle Service:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: User Experience Service
  labels:
    app: User Experience Service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: User Experience Service
  template:
    metadata:
      labels:
        app: User Experience Service
    spec:
      containers:
        - name: User Experience Service
          image: username/User Experience Service:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Accessibility Service
  labels:
    app: Accessibility Service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Accessibility Service
  template:
    metadata:
      labels:
        app: Accessibility Service
    spec:
      containers:
        - name: Accessibility Service
          image: username/Accessibility Service:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Transportation Service
  labels:
    app: Transportation Service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Transportation Service


---


apiVersion: v1
kind: Service
metadata:
  name: Payment Service
  labels:
    app: Payment Service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Payment Service


---


apiVersion: v1
kind: Service
metadata:
  name: Vehicle Service
  labels:
    app: Vehicle Service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Vehicle Service


---


apiVersion: v1
kind: Service
metadata:
  name: User Experience Service
  labels:
    app: User Experience Service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: User Experience Service


---


apiVersion: v1
kind: Service
metadata:
  name: Accessibility Service
  labels:
    app: Accessibility Service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Accessibility Service

