apiVersion: v1
kind: Service
metadata:
  name: Transportation Service
  labels:
    app: Transportation Service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Transportation Service