apiVersion: v1
kind: Service
metadata:
  name: Accessibility Service
  labels:
    app: Accessibility Service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Accessibility Service